### ISSUE TITLE
Link to the docker hub entry

### ISSUE THREAD

**Issue by dreuter** [rust-lang/docker-rust-nightly#1]
Hi :)

Thanks for this image, this makes testing in CI much easier for me. Unfortunately it took me a couple of minutes to find the corresponding docker hub entry. While googling I found this repository, but if you search on docker hub for "rust nightly" you will find a bunch of older unmaintained images. Searching for "rust-lang-nursery" does also not work (which was obvious to me once I found the image).

Maybe you can include this link: https://hub.docker.com/r/rustlang/rust/ in the repo description? Or would you prefer to put it in the README? I personally felt like the description makes more sense considering, that one might fork the project.

Cheers,
Daniel

**Comment by sfackler** [comment]
Good point, fixed!
