### ISSUE TITLE
Can't see the error lines

### ISSUE THREAD

**Issue by iddm** [rust-lang/docker-rust-nightly#17]
Whenever I see errors, the compiler does not show the line causing problems:

```
$ cargo check
   Compiling project v0.1.0 (/home/rust/src)
error[E0061]: this function takes 2 parameters but 1 parameter was supplied

error[E0308]: mismatched types
  |
  = note: expected type `std::string::String`
             found type `&str`

error[E0308]: mismatched types
  |
  = note: expected type `error::Error`
             found type `fn(std::option::Option<_>) -> rocket::response::status::BadRequest<_> {rocket::response::status::BadRequest::<_>}`

error: aborting due to 3 previous errors

Some errors have detailed explanations: E0061, E0308.
For more information about an error, try `rustc --explain E0061`.
error: Could not compile `project`.
```

This is annoying and I have to waste a lot of time commenting out the lines and guessing where could the problem actually be.

**Comment by sfackler** [comment]
This should probably be filed on rust-lang/rust, rather than the docker container.

**Comment by iddm** [comment]
@sfackler I am unsure that this also happens with the `rustc` itself, maybe there is a correlation. As I am unsure and can't investigate further, I filed it here.

**Comment by sfackler** [comment]
This is just a docker image that contains rustc.
