### ISSUE TITLE
Nightly version stuck on 2019-08-22

### ISSUE THREAD

**Issue by tyranron** [rust-lang/docker-rust-nightly#18]
Docker images are pushed to `rustlang/rust` Docker Hub repo every day, however the inner `rustc` version has stuck on `2019-08-22`:
```bash
$ docker pull rustlang/rust:nightly-slim
$ docker run --rm -it rustlang/rust:nightly-slim rustc -V
rustc 1.39.0-nightly (760226733 2019-08-22)
```

While running `rustup` locally corresponds that at least `2019-09-08` version exists:
```bash
$ rustup update nightly
info: syncing channel updates for 'nightly-x86_64-apple-darwin'
info: latest update on 2019-09-09, rust version 1.39.0-nightly (2b8116dce 2019-09-08)
```

**Comment by sfackler** [comment]
Oops - I had caching turned on in Docker Hub which caused all of the layers to be seen as identical. The builds are rerunning now.

**Comment by tyranron** [comment]
@sfackler I suppose this has happened again as now it has stuck on `2019-12-02` version

```bash
$ docker pull rustlang/rust:nightly-slim
$ docker run --rm -it rustlang/rust:nightly-slim rustc -V
rustc 1.41.0-nightly (fdc001156 2019-12-02)
```

Would you be so kind to kick it on once again?

**Comment by sfackler** [comment]
Looks like it broke during the move from rust-lang-nursery to rust-lang. I've pinged the infra team.

**Comment by sfackler** [comment]
Images are rebuilding now!

**Comment by tyranron** [comment]
@sfackler thanks!
