### ISSUE TITLE
Move Repository To rust-lang

### ISSUE THREAD

**Issue by XAMPPRocky** [rust-lang/docker-rust-nightly#21]
Hello, the current `rust-lang-nursery` organisation is considered deprecated, and the Rust Programming Language organisation is trying to consolidate managing Rust's GitHub organisations, as such we'd like you to consider moving your repository to the main `rust-lang` organisation instead. 

### How Do I Move To `rust-lang`?
You most likely won't be able to transfer your repository directly, if so you'll need to transfer your repository to @Mark-Simulacrum, who will then move your repository to the `rust-lang` organisation.

### Deprecating
If you no longer intend to maintain this repository, please let us know and we will take of deprecating the project.

**Comment by sfackler** [comment]
Go for it.

**Comment by XAMPPRocky** [comment]
@sfackler Are you aware if there's any changes needed on the Docker hub side that we should be aware about?

**Comment by sfackler** [comment]
There probably will be, but I can figure those out on my end once the move happens.

Unrelated to this move, but are there any other infra folks I should make admins on the rustlang organization on Docker hub? Right now it's me, alexcrichton, and aidanhs.

**Comment by Mark-Simulacrum** [comment]
Moved it over, pretty sure docker hub should not be affected.

**Comment by XAMPPRocky** [comment]
@sfackler I would expect that it should contain the people in the `infra-admins` sub team. https://github.com/rust-lang/team/blob/master/teams/infra-admins.toml
