### ISSUE TITLE
Prevent images without clippy

### ISSUE THREAD

**Issue by gdesmott** [rust-lang/docker-rust-nightly#22]
`clippy` is not available on some images, breaking CI relying on it. Would it make sense not publishing nightly images where such tools have been broken?

```
error: component 'clippy' for target 'x86_64-unknown-linux-gnu' is unavailable for download for channel nightly
```

**Comment by sfackler** [comment]
Optional components like clippy can be broken for ~weeks at a time, so I don't think it makes sense to not publish images. rustup has some support for searching for nightlies with specific components that you can probably use, but I'm not familiar with the details.

**Comment by gdesmott** [comment]
Fair enough, I'll use a standard image and manually install the nightly version I know is working with clippy then. Thanks!
