### ISSUE TITLE
Publish aarch64 builds

### ISSUE THREAD

**Issue by derdaele** [rust-lang/docker-rust-nightly#26]
When running on Apple Silicon (ARM64 ISA), the current image is emulated and thus slower. It would be nice to have ARM64 images published to docker hub.

Building locally by changing the rustup version to https://static.rust-lang.org/rustup/dist/aarch64-unknown-linux-gnu/rustup-init seems to work.

**Comment by sfackler** [comment]
Ah yeah we should be able to do the same here that was done in the stable images in https://github.com/rust-lang/docker-rust/pull/67. Feel free to make a PR, or I can do it alternatively.

**Comment by derdaele** [comment]
Happy to take a stab at it. 

Any idea on how to actually actually build the arm64 version? docker build uses the host arch by default.
I think we could use docker buildx for that but I'm not sure how to set that up with with travis, any experience with that?

**Comment by sfackler** [comment]
Oh right, we're only publishing x86_64 images right now. It sounds like there's some experimental buildx support on the hub, but it's not super obvious how to use it: https://github.com/docker/hub-feedback/issues/1874
