### ISSUE TITLE
No longer on nightly / Docker image not updated for latest release

### ISSUE THREAD

**Issue by kmccmk9** [rust-lang/docker-rust-nightly#27]
Hello,

I noticed recently our build pipeline started to fail with the following: 
`Installed version: 1.54.0 (2021-05-16)
  Minimum required:  1.54.0-nightly (2021-05-18)`
  This wasn't happening previously. I tried adding a few commands to our CI file to ensure it was on nightly but I keep getting the same error message.
  I've tried both `rustup default nightly` and `rustup override set nightly`.

**Comment by sfackler** [comment]
Do you have a rust-toolchain file forcing the use of the stable channel?

**Comment by kmccmk9** [comment]
No I do not. The project does build locally with my rustup set to nightly. It only fails in the pipeline.

**Comment by sfackler** [comment]
Do you have a minimal self contained example of this issue? I cannot reproduce this behavior:

```bash
bash-5.1$ docker pull rustlang/rust:nightly
nightly: Pulling from rustlang/rust
Digest: sha256:9a399845b33fe9f884287b161248b2fd1d8be1e57e8bad47c63a60150493f5bb
Status: Image is up to date for rustlang/rust:nightly
docker.io/rustlang/rust:nightly
bash-5.1$ docker run rustlang/rust:nightly rustc --version
rustc 1.54.0-nightly (fe72845f7 2021-05-16)
```

**Comment by sfackler** [comment]
Oh sorry, it does look like we aren't updating anymore for some reason! I will investigate.

**Comment by sfackler** [comment]
Ah, it was still building off of Travis CI, but it looks like we've removed that from our org. I'll update it to use Github Actions tonight. In the meantime, running `rustup update nightly` before your build should unblock you.

**Comment by kmccmk9** [comment]
Thank you, that makes sense.

**Comment by kmccmk9** [comment]
No dice:
```
$ rustup update nightly
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: latest update on 2021-05-21, rust version 1.54.0-nightly (40d230204 2021-05-20)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'rustfmt'
info: removing previous version of component 'cargo'
info: rolling back changes
error: could not rename component file from '/usr/local/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/libexec' to '/usr/local/rustup/tmp/mmirj97020d87p2__dir/bk': Invalid cross-device link (os error 18)
```

**Comment by sfackler** [comment]
That seems like a bug in rustup - it should fall back to a copy if unable to rename.

**Comment by sfackler** [comment]
Fixed!
