### ISSUE TITLE
Nightly CI appears to not be working?

### ISSUE THREAD

**Issue by twitchax** [rust-lang/docker-rust-nightly#28]
It has been 8 days since a published image, and was wondering whether I might need to find an alternative.

**Comment by sfackler** [comment]
We are set up to have the images built on Docker Hub's automated build infrastructure, but that's no longer available on their free tier. I've pinged the infra folks to see what the best option is moving forward.

**Comment by sfackler** [comment]
We now publish the images to the Github container registry: https://github.com/rust-lang/docker-rust-nightly/pkgs/container/rust. We'll get the Docker Hub publishing back up as well but it may take a day or two.

**Comment by twitchax** [comment]
Awesome: makes sense!  Appreciate the update. :)

**Comment by sfackler** [comment]
We are now publishing to Docker Hub again!
