### ISSUE TITLE
Not published to Docker Hub

### ISSUE THREAD

**Issue by tyranron** [rust-lang/docker-rust-nightly#31]
Somehow nightly images are not published on Docker Hub.

<img width="631" alt="Screenshot 2021-08-10 at 10 43 13" src="https://user-images.githubusercontent.com/7114909/128828274-210bf913-45b5-4f28-bc16-d38c05db2695.png">

While at the same time on GHCR everything is OK.

<img width="785" alt="Screenshot 2021-08-10 at 10 44 24" src="https://user-images.githubusercontent.com/7114909/128828429-b184944e-9ace-49da-822f-612b933577e9.png">

**Comment by sfackler** [comment]
#28

**Comment by sfackler** [comment]
We are now publishing to Docker Hub again!
