### ISSUE TITLE
Outdated Image

### ISSUE THREAD

**Issue by reneklacan** [rust-lang/docker-rust-nightly#4]
At this point docker hub contains 4 days old image

![image](https://user-images.githubusercontent.com/1935686/38468487-eef997c8-3b46-11e8-811c-859b3d25a69f.png)

Problem is probably caused by queued old build.

**Comment by sfackler** [comment]
I emailed Docker support to see if they can unblock things. Hopefully they'll get it working again!

**Comment by reneklacan** [comment]
Thank you, it's fixed now 🎉
