### ISSUE TITLE
rustup-init is installing out of date nightly rustc version

### ISSUE THREAD

**Issue by chucksmash** [rust-lang/docker-rust-nightly#5]
I'm working off of the `rustlang/rust:nightly` tag to allow for compiling Rocket.

It looks like the docker image for rustlang/rust:nightly currently has rustc version `1.27.0-nightly (2018-04-18)` but version `1.27.0-nightly (2018-04-26)` is available. This causes the compilation of my app to fail.

As an attempted workaround, I copied the contents of the relevant Dockerfile and tried to run them myself:

``` Dockerfile
FROM rustlang/rust:nightly AS build


ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:$PATH

RUN set -eux; \
    \
    url="https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init"; \
    wget "$url"; \
    chmod +x rustup-init; \
    ./rustup-init -y --no-modify-path --default-toolchain nightly; \
    rm rustup-init; \
    chmod -R a+w $RUSTUP_HOME $CARGO_HOME; \
    rustup --version; \
    cargo --version; \
    rustc --version;
```

This still installs the old version of rustc however:

```
+ rustup --version
rustup 1.11.0 (e751ff9f8 2018-02-13)
+ cargo --version
cargo 1.26.0-nightly (008c36908 2018-04-13)
+ rustc --version
rustc 1.27.0-nightly (ac3c2288f 2018-04-18)
```

**Comment by sfackler** [comment]
Seems like that'd be a bug with rustup rather than the docker image, right?

**Comment by chucksmash** [comment]
Fair point :+1:
