### ISSUE TITLE
cargo-clippy can't be executed

### ISSUE THREAD

**Issue by gnuvince** [rust-lang/docker-rust-nightly#9]
If I run a container off of the image `rustlang/rust:16da53969981`, I'm unable to run clippy.

```
$ docker container run --rm -it rustlang/rust:nightly bash
root@2255dba279d5:/# which cargo-clippy
/usr/local/cargo/bin/cargo-clippy
root@2255dba279d5:/# cargo-clippy
error: toolchain 'nightly-x86_64-unknown-linux-gnu' does not have the binary `cargo-clippy`
root@2255dba279d5:/# 
```

**Comment by sfackler** [comment]
Some nightlies don't have all tools available.

**Comment by gnuvince** [comment]
So use `rustup` to install it and ensure it's there?

**Comment by sfackler** [comment]
The `cargo-clippy` binary in `/usr/local/cargo/bin/cargo-clippy` is just a proxy. You also need to have the cargo-clippy rustup component installed to use it. The Docker image installs a minimal set of functionality, and consumers can pull extra parts on themselves.

**Comment by gnuvince** [comment]
Cool, thanks.
